import fs from 'node:fs';
import path from 'node:path';
import {
  repoRoot,
  readJson,
  writeText,
  sourceLockPath,
  resourcePath,
  generatedPath,
  generateProperties,
  escapeXml,
  csharpStringLiteral
} from './lib.mjs';

const lock = readJson(sourceLockPath);
const packageRoot = path.join(repoRoot, 'node_modules/@iconify-json/lets-icons');
const packageJsonPath = path.join(packageRoot, 'package.json');
const iconsPath = path.join(packageRoot, 'icons.json');
const infoPath = path.join(packageRoot, 'info.json');
const metadataPath = path.join(packageRoot, 'metadata.json');

for (const file of [packageJsonPath, iconsPath, infoPath]) {
  if (!fs.existsSync(file)) {
    console.error(`Missing ${path.relative(repoRoot, file)}.`);
    console.error('Run npm install first, or run tools\\commands\\bootstrap.cmd.');
    process.exit(2);
  }
}

const packageJson = readJson(packageJsonPath);
if (packageJson.version !== lock.version) {
  throw new Error(`Source package version mismatch. Expected ${lock.version}, found ${packageJson.version}.`);
}

const icons = readJson(iconsPath);
const info = readJson(infoPath);
const metadata = fs.existsSync(metadataPath) ? readJson(metadataPath) : {};
const names = Object.keys(icons.icons ?? {}).sort((a, b) => a.localeCompare(b));

if (names.length !== lock.expectedCanonicalIconCount) {
  throw new Error(
    `Icon count mismatch. Expected ${lock.expectedCanonicalIconCount}, found ${names.length}. ` +
    'Update SOURCE-LOCK.json deliberately when upgrading the upstream source.'
  );
}

const properties = generateProperties(names);
const propertyByName = Object.fromEntries(properties.map(item => [item.name, item.identifier]));
const normalizedIcons = Object.fromEntries(names.map(name => [
  name,
  { ...icons.icons[name], csharpProperty: propertyByName[name] }
]));

const combined = {
  prefix: icons.prefix ?? 'lets-icons',
  info,
  source: {
    mode: 'canonical',
    package: lock.source,
    version: lock.version,
    figmaCommunityFile: lock.figmaCommunityFile,
    license: lock.license
  },
  icons: normalizedIcons,
  aliases: icons.aliases ?? {},
  categories: metadata.categories ?? {},
  themes: metadata.themes ?? {},
  width: icons.width ?? 24,
  height: icons.height ?? 24
};

writeText(resourcePath, JSON.stringify(combined, null, 2) + '\n');

const lines = [
  '// <auto-generated />',
  '// Generated by tools/icons/sync-icons.mjs. Do not edit by hand.',
  'namespace ShadBlazor.FreeIcon;',
  '',
  'public static partial class FreeIcons',
  '{',
  `    public const int Count = ${names.length};`,
  ''
];

for (const { name, identifier } of properties) {
  lines.push(`    /// <summary>Lets Icons: ${escapeXml(name)}</summary>`);
  lines.push(`    public static FreeIconData ${identifier} => FreeIconRegistry.Get("${csharpStringLiteral(name)}");`);
  lines.push('');
}

lines.push('}', '');
writeText(generatedPath, lines.join('\n'));

console.log(`Synced ${names.length} Lets Icons glyphs from ${lock.source}@${lock.version}.`);
console.log(`  Resource : ${path.relative(repoRoot, resourcePath)}`);
console.log(`  C# API   : ${path.relative(repoRoot, generatedPath)}`);
